### ISSUE TITLE
Official support for jenkins

### ISSUE THREAD

**Issue by roisec** [turbot/steampipe-plugin-jenkins#2]
Hi, There is any official support for jenkins soon?

**Comment by misraved** [comment]
Thanks @roisec for expressing interest in this plugin 👍.

I believe https://github.com/turbot/steampipe-plugin-jenkins/pull/1 can be compiled and used locally.

Currently, it's on hold due to other priorities, but you can build it locally and start using it.

Feedbacks are more than welcome 👍.

**Comment by cbruno10** [comment]
Hey @roisec , we've started looking at this plugin again and are verifying the design before we release it. As @misraved mentioned, the current build off of the `bootstrap` branch should be usable locally, if you're interested in testing it out.

Also, if you have time, can you please share what Jenkins plugins (if any) you're currently using today that we should look to test from our end?

Once we officially release the plugin though we'll let you know!

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-jenkins/commit/14738e38d7d72ff7f942ef608ef0900a686c0c29

**Comment by misraved** [comment]
Thanks @roisec once again for expressing interest in this plugin.

We have now officially released it. Please feel free to install it using `steampipe plugin install jenkins`.

Would love to know how you find this plugin and if changes/enhancements are needed to better fit your use case 👍.
