### ISSUE TITLE
Get users functionality

### ISSUE THREAD

**Issue by IvenGe** [turbot/steampipe-plugin-jenkins#4]
A way to query all the jenkins users

**Comment by IvenGe** [comment]
Currently the plugin does not have functionality to list all Jenkins users.  
In order to query all user modification on plugin and dependent libraries are required.
I already made modifications in the gojenkins dependency and this repository. 

However it needs to be reviewed: 
https://github.com/turbot/steampipe-plugin-jenkins/compare/main...IvenGe:steampipe-plugin-jenkins:main
https://github.com/bndr/gojenkins/compare/master...IvenGe:gojenkins:master
Hope it helps!

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-jenkins/pull/8

**Comment by codenio** [comment]
@IvenGe @misraved, please reopen the issue.
I would like to work on this
